### ISSUE TITLE
Latest Nuxt.js version

### ISSUE THREAD

**Issue by BeerK0in** [kamatte-me/nuxt-firebase-pwa#2]
@kamatte-me Do you know a way to use a later version of Nuxt.js than 1.0.0-rc11? Cloud Functions only supports Node.js 6 but the newer Nuxt.js versions require Node.js 8.

**Comment by kamatte-me** [comment]
Hi @BeerK0in .

There is currently no way to use Nuxt.js than 1.0.0-rc11 with Cloud Functions.
As you say, Cloud Fuctions only supports Node.js v6. And the last Nuxt version available for Node.js v6 is 1.0.0-rc11.

I also want to use the latest Nuxt.js. 😭
I'm watching a release notes of Cloud Functions...[Release Notes](https://cloud.google.com/functions/docs/release-notes)
I will update this repository when newer Node.js become available in Cloud Functions !

**Comment by yudppp** [comment]
Hi @kamatte-me 

> Support for new runtimes: Node.js 8 and Python, in Beta.
( https://cloud.google.com/functions/docs/release-notes )

Cloud Fuctions supports Node.js v8:tada:
I want to use latest Nust.js version.Please upgrade modules.

**Comment by kamatte-me** [comment]
@yudppp 
Thank you for telling me! And, sorry for being late.
**I uploaded this repository so that we can use Node.js v8 just now!!!** I also updated latest version of Nuxt.js.
In Node.js v8, both the package and the code have been simplified.

Enjoy🚀
